### PR TITLE
Throat surgery!

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Makes a BRAND NEW THROAT SURGERY!
Wiki already updated:
http://wiki.atlas-station.com/Surgery#Cut-throat_surgery
Also makes a new paper spawn in surgery for people to take a look at.

Also includes a critical bug fix for meatspikes.

### CODE REVIEW

**Comment by Chronitonity** [comment]
id prefer if you added an alternative to synthetic skin to use for ghetto surgery.

**Comment by Crystalwarrior** [comment]
Yeah, I also have to add examine text and fix the paper in surgery.

**Comment by Crystalwarrior** [comment]
Ayyy, you can merge now

**Comment by Chronitonity** [comment]
Aite, still want that synthetic skin to do something else besides only be used for throat surgery in the future.

**Pull request merged**
