### PR TITLE
Abduction update 1 [WIP]

### PR DESCRIPTION
**Pull request by whitefox08**

### CODE REVIEW

**Comment by Chronitonity** [comment]
IM WHITEFOX I ADD DO NOT MERGE TO MY OWN COMMITS WITHOUT SAYING WHY ALSO I HAVE A BAD BEARD

**Comment by whitefox08** [comment]
YOU HAVE BALLS SAYINF SOMTHING LIKE THERE KID!

**Comment by Chronitonity** [comment]
HI IM WHITEFOX AND I NEVER UPDATE MY COMMITS TO TELL CHRON, MY KING, THE STATUS OF THIS.

**Comment by whitefox08** [comment]
IM GOING TO CRASH THIS PLANE, NO SURVIVORS!

**Pull request closed without merging**
