### PR TITLE
Ports VG's DeityLink's new explosion method 

### PR DESCRIPTION
**Pull request by Crystalwarrior**
* Ports /vg/ DeityLink's new explosion effect
* Blast doors are more resistant to explosions
* Engine floors (black hexagon ones) are more resistant to explosions
* Explosions can now be affected by Walls and Doors (Cheaper than recursive explosions!)
* Adds config option for new explosion effect (Defaults to on, It's nicer, it's still cheap to run, etc.)
* Adds debug verb for displaying the range and effect of various explosions

Thanks also to RR tgstation/-tg-station#9412

### CODE REVIEW

**Comment by Chronitonity** [comment]
:+1:

**Comment by Chronitonity** [comment]
But in my heart I knew I
Wasn't the only one
Cause when the tables turned
He had to break up

**Comment by Crystalwarrior** [comment]
wat

**Comment by DeityLink** [comment]
Ohey, aren't you guys the bastards who betrayed Hippie or something? I'd love to hear your side of the story.

**Comment by Crystalwarrior** [comment]
@DeityLink https://www.reddit.com/r/SS13/comments/33j4gi/hippie_station_admin_team_migration_drama/
Wouldn't really call it a "betrayal", honestly.

**Comment by DeityLink** [comment]
Thanks for the link. Well at least I'm glad things got resolved for both servers. More SS13 communities can't be a bad thing.
Everyone is welcome to port our features.

**Pull request merged**
