### PR TITLE
Pixel projectiles!

### PR DESCRIPTION
**Pull request by Crystalwarrior**
Makes most of the projectiles use pixel offset. They will move tile if pixel_x/y is outside the bounds. You can still use the legacy system per-bullet, like fireballs currently.
Proper spreading is implemented for shotguns and other scattershots.
Video in action:
http://puu.sh/hFXpX/294fe4345d.webm

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Can you give a few details on some files? Are they needed for the project or just test stuff?

code/WorkInProgress/crystalwarrior160/pixelprojectiles.dm 
icons/wip/projectiles.dmi

Also, what icon changes did you have to implement?

**Comment by Nienhaus** [comment]
Isn't it supposed to be hard to port TG gun stuff to Bay?

**Comment by ZomgPonies** [comment]
Wasn't it supposed to be impossible to port LINDA to bay? ;)

**Comment by Nienhaus** [comment]
I don't know, I don't know anything about that kind of stuff really. I know more about gun code. It might be better to just port TG gun code to bay.

**Comment by Crystalwarrior** [comment]
@ZomgPonies the WIP code you can get rid of, and wip/projectiles.dmi is just for safe keeping of original sprites.
I haven't seen Bay's projectile code but based on my experiences on Colonial Marines it's just as god-awful as /tg/ projectile code.
Fun fact, I mostly only touched projectile's fire code and variance variables on ammo casings - variance is measured in degrees now, so if you want a 30 degree spread for say shotguns you can just set variance to that on the buckshot rounds and call it a day.
You can also toggle between randomspread and smart spread. Just set "randomspread" variable to 1 on the ammo casing, it's off by default so shotguns are consistently awesome.

If you need my help don't be afraid to message me on skype or steam (My nickname is Crystalwarrior160, display name Jack Noir). I'll take a look at the way baycode does projectiles and see if I can figure out the differences.

**Comment by ZomgPonies** [comment]
Added you to Steam. There's a ridiculous amount of Jack Noir's on Skype, and only one Crystalwarrior160 (from Russia), so I couldn't find you there.

**Comment by Crystalwarrior** [comment]
I'm Russian, hah.

**Comment by Fox-McCloud** [comment]
Question---this broke reflecting of projectiles on our server---did it have the same impact on yours? If so, is it broken on yours, as well? If not, any ideas why...if it is broken, plan on implementing a fix?

**Comment by JamieH** [comment]
I'm not 100% sure we intended it to have reflective projectiles, since I'm 95% sure we don't have them at all, might have needed some modification in the PR

**Comment by Fox-McCloud** [comment]
Given that you're a TG branch, you most certainly do: 

https://github.com/AtlasStation/AtlasStation/blob/53a4440901f38b41607a715c1b8b7c43d3190deb/code/modules/mob/living/carbon/human/human_defense.dm#L99

https://github.com/AtlasStation/AtlasStation/blob/53a4440901f38b41607a715c1b8b7c43d3190deb/code/modules/mob/living/carbon/human/human_defense.dm#L44

**Comment by Crystalwarrior** [comment]
@Fox-McCloud Alright, it's going to be fixed soonish

**Comment by Fox-McCloud** [comment]
@Crystalwarrior 

May want to disable pixel-based projectiles and test it out to get an idea/feel for what it does before delving into it; just a suggestion!

**Comment by Crystalwarrior** [comment]
@Fox-McCloud DOn't worry, I got this. It seems like it fucks up because Angle is not reset.

**Pull request merged**
