### PR TITLE
Adds in Hangers for Space pods! [WIP]

### PR DESCRIPTION
**Pull request by whitefox08**
1tvrjfw

TODO:
1. Do more passes on the main hanger
2. Add Department hangers 
3. Hanger door Sprites

### CODE REVIEW

**Comment by whitefox08** [comment]
y5pl3nn

Did another pass, for the main hanger, moved construction around and Secure storage.

cmfnmth

Security pod bay(yes i know a floating apc)

**Comment by HoaxIT** [comment]
Second main hangar, makes secure storage, insecure.

**Comment by whitefox08** [comment]
@HoaxIT Yea, this is the only problem I ran into when making this, I could wall it up with R walls or use crystal glass. But at the same time its in a more open area so people will be less likely to take it.

**Comment by JamieH** [comment]
@whitefox08 replace it with crystal glass, that stuff is a PAIN to break.

**Comment by whitefox08** [comment]
@JamieH But again we run into the same problem of crystal windows being able to be removed via screwdriver and crowbar.

**Comment by whitefox08** [comment]
Did a final pass, Engineering Bay added. For now SS is going to be regular walled for now. 

fylp8ii
xphfm3m

**Comment by Nienhaus** [comment]
Didn't I sprite a four wide door for you?

**Pull request merged**
